[[redirects]]
  from = "/2023/en/*"
  to = "/2023/en/index.html"
  status = 200

[[redirects]]
  from = "/2023/users/*"
  to = "/2023/200.html"
  status = 200

[[redirects]]
  from = "/2023/*"
  to = "/2023/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/2023/:splat"
  status = 301

[functions.server]
  external_node_modules = ["chrome-aws-lambda"]
