name: Node.js CI

on:
  # push:
  #   branches:
  #     - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.16.0]

    steps:
      - uses: actions/checkout@v3

      - name: Install packages
        uses: ./.github/actions/install-packages

      - name: Lint check
        run: pnpm lint

  typecheck:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.16.0]

    steps:
      - uses: actions/checkout@v3

      - name: Install packages
        uses: ./.github/actions/install-packages

      - name: Type check
        run: pnpm typecheck

  unit-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.16.0]

    steps:
      - uses: actions/checkout@v3

      - name: Install packages
        uses: ./.github/actions/install-packages

      - name: Unit test
        run: pnpm vitest

  integration-test:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node18.12.0-chrome106-ff106
      options: --user 1001

    steps:
      - uses: actions/checkout@v4

      - name: Install packages
        uses: ./.github/actions/install-packages

      - name: Integration test
        run: pnpm cypress:ci
        env:
          SUPABASE_URL: ${{ secrets.NUXT_SUPABASE_PROJECT_URL }}
          SUPABASE_KEY: ${{ secrets.NUXT_SUPABASE_API_KEY }}

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress videos
          path: ./tests/cypress/videos
