name: Node.js CI

on:
  # push:
  #   branches:
  #     - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.18.1]

    steps:
      - uses: actions/checkout@v3

      - name: Install packages
        uses: ./.github/actions/install-packages

      - name: Lint check
        run: pnpm lint

  typecheck:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.18.1]

    steps:
      - uses: actions/checkout@v3

      - name: Install packages
        uses: ./.github/actions/install-packages

      - name: Type check
        run: pnpm typecheck

  unit-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.18.1]

    steps:
      - uses: actions/checkout@v3

      - name: Install packages
        uses: ./.github/actions/install-packages

      - name: Unit test
        run: pnpm test

  integration-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.18.1]

    steps:
      - uses: actions/checkout@v3

      - name: Install packages
        uses: ./.github/actions/install-packages

      - name: Integration test
        run: pnpm cypress:ci
